name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: myapp

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova
      working-directory: myapp

    - name: Install project dependencies
      run: npm install
      working-directory: myapp

    - name: Add iOS platform
      run: cordova platform add ios
      working-directory: myapp

    - name: Build IPA
      run: cordova build ios --release
      working-directory: myapp

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: myapp/platforms/ios/build/**/*.ipa
